### Common Python Tools for Data Science

Numerical Python - NumPy 
Pandas
Matplotlib / Seaborn
SciPy

Computational Libraries

In [2]:
import numpy as np

### Numpy is largely like a more scalable array


In [5]:

# instantiation
arr = np.array([0,1,2,3,4])
arr

array([0, 1, 2, 3, 4])

In [7]:
# reading from csv (also works for tsv and other "separated value formats")
arr =  np.genfromtxt('example.csv', delimiter=',')
arr

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [8]:
# n - dimensional data
arr_4d = np.zeros((2, 2, 3, 4))  # 4D array with shape (2, 2, 3, 4)
print(arr_4d)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
